### ISSUE TITLE
Bug when using aoe spell

### ISSUE THREAD

**Issue by alien4rmspace** [nisovin/MagicSpells#38]
`[10:22:08] [Server thread/WARN]: FieldAccessException: Field index out of bounds. (Index: 3, Size: 3)
[10:22:08] [Server thread/WARN]:    at com.comphenix.protocol.reflect.StructureModifier.writeInternal(StructureModifier.java:352)
[10:22:08] [Server thread/WARN]:    at com.comphenix.protocol.reflect.StructureModifier.write(StructureModifier.java:328)
[10:22:08] [Server thread/WARN]:    at com.nisovin.magicspells.volatilecode.VolatileCodeProtocolLib.playSound(VolatileCodeProtocolLib.java:31)
[10:22:08] [Server thread/WARN]:    at com.nisovin.magicspells.spelleffects.SoundEffect.playEffectLocation(SoundEffect.java:46)
[10:22:08] [Server thread/WARN]:    at com.nisovin.magicspells.spelleffects.SpellEffect.playEffectLocationReal(SpellEffect.java:128)
[10:22:08] [Server thread/WARN]:    at com.nisovin.magicspells.spelleffects.SpellEffect.playEffectEntity(SpellEffect.java:95)
[10:22:08] [Server thread/WARN]:    at com.nisovin.magicspells.spelleffects.SpellEffect.playEffect(SpellEffect.java:84)
[10:22:08] [Server thread/WARN]:    at com.nisovin.magicspells.Spell.playSpellEffects(Spell.java:1478)
[10:22:08] [Server thread/WARN]:    at com.nisovin.magicspells.spells.targeted.AreaEffectSpell.doAoe(AreaEffectSpell.java:213)
[10:22:08] [Server thread/WARN]:    at com.nisovin.magicspells.spells.targeted.AreaEffectSpell.castSpell(AreaEffectSpell.java:128)
[10:22:08] [Server thread/WARN]:    at com.nisovin.magicspells.Subspell.castReal(Subspell.java:138)
[10:22:08] [Server thread/WARN]:    at com.nisovin.magicspells.Subspell.cast(Subspell.java:120)
[10:22:08] [Server thread/WARN]:    at com.nisovin.magicspells.spells.MultiSpell.castSpell(MultiSpell.java:88)
[10:22:08] [Server thread/WARN]:    at com.nisovin.magicspells.Spell.handleCast(Spell.java:801)
[10:22:08] [Server thread/WARN]:    at com.nisovin.magicspells.Spell.cast(Spell.java:725)
[10:22:08] [Server thread/WARN]:    at com.nisovin.magicspells.Spell.cast(Spell.java:714)
[10:22:08] [Server thread/WARN]:    at com.nisovin.magicspells.CastCommand.onCommand(CastCommand.java:193)
[10:22:08] [Server thread/WARN]:    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[10:22:08] [Server thread/WARN]:    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:152)
[10:22:08] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_9_R2.CraftServer.dispatchCommand(CraftServer.java:665)
[10:22:08] [Server thread/WARN]:    at net.minecraft.server.v1_9_R2.PlayerConnection.handleCommand(PlayerConnection.java:1387)
[10:22:08] [Server thread/WARN]:    at net.minecraft.server.v1_9_R2.PlayerConnection.chat(PlayerConnection.java:1296)
[10:22:08] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_9_R2.entity.CraftPlayer.chat(CraftPlayer.java:331)
[10:22:08] [Server thread/WARN]:    at think.rpgitems.power.PowerCommand.executeCommand(PowerCommand.java:75)
[10:22:08] [Server thread/WARN]:    at think.rpgitems.power.PowerCommand.rightClick(PowerCommand.java:84)
[10:22:08] [Server thread/WARN]:    at think.rpgitems.item.RPGItem.rightClick(RPGItem.java:317)
[10:22:08] [Server thread/WARN]:    at think.rpgitems.Events.onPlayerAction(Events.java:232)
[10:22:08] [Server thread/WARN]:    at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor325.execute(Unknown Source)
[10:22:08] [Server thread/WARN]:    at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44)
[10:22:08] [Server thread/WARN]:    at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78)
[10:22:08] [Server thread/WARN]:    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[10:22:08] [Server thread/WARN]:    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517)
[10:22:08] [Server thread/WARN]:    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502)
[10:22:08] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_9_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:231)
[10:22:08] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_9_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:198)
[10:22:08] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_9_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:194)
[10:22:08] [Server thread/WARN]:    at net.minecraft.server.v1_9_R2.PlayerConnection.a(PlayerConnection.java:946)
[10:22:08] [Server thread/WARN]:    at net.minecraft.server.v1_9_R2.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:27)
[10:22:08] [Server thread/WARN]:    at net.minecraft.server.v1_9_R2.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:5)
[10:22:08] [Server thread/WARN]:    at net.minecraft.server.v1_9_R2.PlayerConnectionUtils$1.run(SourceFile:13)
[10:22:08] [Server thread/WARN]:    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[10:22:08] [Server thread/WARN]:    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[10:22:08] [Server thread/WARN]:    at net.minecraft.server.v1_9_R2.SystemUtils.a(SourceFile:45)
[10:22:08] [Server thread/WARN]:    at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:786)
[10:22:08] [Server thread/WARN]:    at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:403)
[10:22:08] [Server thread/WARN]:    at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:723)
[10:22:08] [Server thread/WARN]:    at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:622)
[10:22:08] [Server thread/WARN]:    at java.lang.Thread.run(Thread.java:745)`

**Comment by maitmd** [comment]
Seems like it has something to do with any effects attached to it.
